name: on pr comment
on:
  issue_comment:
    types: [created]

jobs:
  on_pr_comment:
    name: Trigger message
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith( github.event.comment.body, '!test' ) }}
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v7
        with:
          script: |
            const prComment = process.env.COMMENT;
            const commentRegex = /!test ([a-zA-Z0-9_\-]*)/gm;
            const match = prComment.match(commentRegex);

            const prNumber = Number(process.env.PR_NUMBER);

            console.log(match, prNumber, prComment);

            if (match) {
              const ruleName = match[1];

              const response = await github.rest.pulls.get({
                owner: 'corwin-gs',
                repo: 'actions',
                pull_number: prNumber
              });

              const { data: pullRequest } = response;

              console.log(pullRequest, response);

              const thisBranchNameSlug = pullRequest.head.ref.replace(/[^a-zA-Z0-9]/g, '-').replace(/^-*/, '').replace(/-*$/, '');

              const branchMessage = `The branch is ${thisBranchNameSlug}`

              console.log(branchMessage, thisBranchNameSlug);

              await github.rest.issues.createComment({
                owner: 'corwin-gs',
                repo: 'actions',
                issue_number: prNumber,
                body: branchMessage
              });
            }
        env:
          COMMENT: ${{ github.event.comment.body }}
          PR_NUMBER: ${{ github.event.issue.number }}
