name: on pr comment
on:
  issue_comment:
    types: [created]

jobs:
  start_load_test:
    name: Trigger message
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith('!test', github.event.issue_comment.comment.body) }}
    steps:
      - name: Trigger workflow
        uses: actions/github-script@v7
        with:
          script: |
            const prComment = process.env.COMMENT;
            const commentRegex = /!test ([a-zA-Z0-9_\-]*)/gm;
            const match = prComment.matches(commentRegex);

            const prNumber = Number(process.env.PR_NUMBER);

            if (match) {
              const ruleName = match[1];

              const { data: pullRequest } = github.rest.pulls.get({
                owner: 'corwin-gs',
                repo: 'actions',
                pull_number: prNumber
              });

              const thisBranchNameSlug = pullRequest.head.ref.replace(/[^a-zA-Z0-9]/g, '-').replace(/^-*/, '').replace(/-*$/, '');

              const branchMessage = `The branch is ${thisBranchNameSlug}`

              await github.rest.issues.createComment({
                owner: 'corwin-gs',
                repo: 'actions',
                issue_number: prNumber,
                body: branchMessage
              });
            }
        env:
          COMMENT: ${{ github.event.issue_comment.comment.body }}
          PR_NUMBER: ${{ github.event.issue.id }}
